repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        name: black (check-only)
        args: [--check, --diff]
        language_version: python3.11
        exclude: ^(dynex/proto/|examples/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (check-only)
        args: [--check-only, --diff]
        exclude: ^(dynex/proto/|examples/)

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, "--extend-ignore=E203,W503"]
        exclude: ^examples/
