# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dynex.proto import sdk_pb2 as pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pkg/proto/sdk/v2/sdk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDKStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.stream_unary(
                '/dynex.sdk.v2.SDK/CreateJob',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CreateJobReply.FromString,
                _registered_method=True)
        self.EstimateJob = channel.unary_unary(
                '/dynex.sdk.v2.SDK/EstimateJob',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.EstimateJobRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.EstimateJobReply.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/dynex.sdk.v2.SDK/CancelJob',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CancelJobReply.FromString,
                _registered_method=True)
        self.FinishJob = channel.unary_unary(
                '/dynex.sdk.v2.SDK/FinishJob',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.FinishJobRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.FinishJobReply.FromString,
                _registered_method=True)
        self.UpdateJob = channel.unary_unary(
                '/dynex.sdk.v2.SDK/UpdateJob',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.UpdateJobRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.UpdateJobReply.FromString,
                _registered_method=True)
        self.SubscribeJob = channel.unary_stream(
                '/dynex.sdk.v2.SDK/SubscribeJob',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.SubscribeJobRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.JobEvent.FromString,
                _registered_method=True)
        self.DownloadSolution = channel.unary_stream(
                '/dynex.sdk.v2.SDK/DownloadSolution',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.DownloadSolutionRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.SolutionChunk.FromString,
                _registered_method=True)
        self.ListAtomics = channel.unary_unary(
                '/dynex.sdk.v2.SDK/ListAtomics',
                request_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.ListAtomicsRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.ListAtomicsReply.FromString,
                _registered_method=True)


class SDKServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request_iterator, context):
        """Jobs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeJob(self, request, context):
        """Events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadSolution(self, request, context):
        """Solutions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAtomics(self, request, context):
        """Atomics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDKServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CreateJobRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CreateJobReply.SerializeToString,
            ),
            'EstimateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateJob,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.EstimateJobRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.EstimateJobReply.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CancelJobRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CancelJobReply.SerializeToString,
            ),
            'FinishJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishJob,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.FinishJobRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.FinishJobReply.SerializeToString,
            ),
            'UpdateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJob,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.UpdateJobRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.UpdateJobReply.SerializeToString,
            ),
            'SubscribeJob': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeJob,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.SubscribeJobRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.JobEvent.SerializeToString,
            ),
            'DownloadSolution': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadSolution,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.DownloadSolutionRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.SolutionChunk.SerializeToString,
            ),
            'ListAtomics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAtomics,
                    request_deserializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.ListAtomicsRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.ListAtomicsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynex.sdk.v2.SDK', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynex.sdk.v2.SDK', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDK(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dynex.sdk.v2.SDK/CreateJob',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CreateJobRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CreateJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynex.sdk.v2.SDK/EstimateJob',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.EstimateJobRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.EstimateJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynex.sdk.v2.SDK/CancelJob',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CancelJobRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.CancelJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynex.sdk.v2.SDK/FinishJob',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.FinishJobRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.FinishJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynex.sdk.v2.SDK/UpdateJob',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.UpdateJobRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.UpdateJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dynex.sdk.v2.SDK/SubscribeJob',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.SubscribeJobRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dynex.sdk.v2.SDK/DownloadSolution',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.DownloadSolutionRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.SolutionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAtomics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynex.sdk.v2.SDK/ListAtomics',
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.ListAtomicsRequest.SerializeToString,
            pkg_dot_proto_dot_sdk_dot_v2_dot_sdk__pb2.ListAtomicsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
